#!/usr/bin/env node
/**
 * Markdown content build pipeline for thequeenwedding.kr
 * Scans content/, generates HTML pages, RSS, sitemap, and updates index.html
 */

const fs = require('fs');
const path = require('path');
const matter = require('gray-matter');
const { marked } = require('marked');

const ROOT = path.resolve(__dirname, '..');
const CONTENT_DIR = path.join(ROOT, 'content');
const TEMPLATES_DIR = path.join(ROOT, 'templates');

const SITE_URL = 'https://thequeenwedding.kr';
const LOGO_URL = 'https://i.ibb.co/Ngw5GBKq/1.jpg';
const KAKAO_JS_KEY = (process.env.KAKAO_JS_KEY || '').trim();
const AUTO_COMMENT = '<!-- AUTO-GENERATED by scripts/build-content.js — DO NOT EDIT MANUALLY -->\n';

const CATEGORIES = ['news', 'guide', 'stories', 'dining'];

const CATEGORY_LABELS = {
  news: '더퀸 소식',
  guide: '웨딩 가이드',
  stories: '리얼 웨딩',
  dining: '퀸즈테이블',
};

const CATEGORY_INTROS = {
  news: '더퀸 웨딩홀의 공식 소식, 박람회·프로모션, 보도자료를 전해드립니다.',
  guide: '포항 결혼 준비를 위한 실용적인 웨딩 가이드와 체크리스트를 모았습니다.',
  stories: '갤럭시홀·크라운홀에서 펼쳐진 리얼 웨딩의 감동적인 순간들을 담았습니다.',
  dining: '퀸즈테이블의 프리미엄 다이닝 이야기와 메뉴 소개를 만나보세요.',
};

const BASE_SITEMAP_URLS = [
  { loc: `${SITE_URL}/`, changefreq: 'weekly', priority: '1.0' },
  { loc: `${SITE_URL}/hall-galaxy`, changefreq: 'monthly', priority: '0.9' },
  { loc: `${SITE_URL}/buffet`, changefreq: 'monthly', priority: '0.85' },
  { loc: `${SITE_URL}/gallery`, changefreq: 'monthly', priority: '0.8' },
  { loc: `${SITE_URL}/directions`, changefreq: 'monthly', priority: '0.8' },
  { loc: `${SITE_URL}/reviews`, changefreq: 'monthly', priority: '0.75' },
  { loc: `${SITE_URL}/queens-table`, changefreq: 'weekly', priority: '0.9' },
  { loc: `${SITE_URL}/dress-show`, changefreq: 'monthly', priority: '0.7' },
];

marked.setOptions({ gfm: true, breaks: false });

function readFile(filePath) {
  return fs.readFileSync(filePath, 'utf8');
}

function writeFile(filePath, content) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, 'utf8');
}

function escapeHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function toAbsoluteUrl(url) {
  if (!url) return LOGO_URL;
  if (url.startsWith('http://') || url.startsWith('https://')) return url;
  return `${SITE_URL}${url.startsWith('/') ? '' : '/'}${url}`;
}

function formatDateDisplay(dateStr) {
  const d = new Date(dateStr);
  if (Number.isNaN(d.getTime())) return dateStr;
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}.${m}.${day}`;
}

function toRfc822(dateStr) {
  const d = new Date(dateStr);
  if (Number.isNaN(d.getTime())) return new Date().toUTCString();
  return d.toUTCString();
}

function replaceAll(template, vars) {
  let result = template;
  for (const [key, value] of Object.entries(vars)) {
    result = result.split(`{{${key}}}`).join(value ?? '');
  }
  return result;
}

function scanPosts() {
  const posts = [];

  function walk(dir) {
    if (!fs.existsSync(dir)) return;
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(full);
      } else if (entry.isFile() && entry.name.endsWith('.md')) {
        const raw = readFile(full);
        const { data, content } = matter(raw);
        if (data.draft === true) continue;

        const category = data.category || path.basename(path.dirname(full));
        const slug = data.slug || entry.name.replace(/^\d{4}-\d{2}-\d{2}-/, '').replace(/\.md$/, '');

        posts.push({
          filePath: full,
          title: data.title || slug,
          description: data.description || '',
          date: String(data.date || '1970-01-01'),
          category,
          slug,
          thumbnail: data.thumbnail || LOGO_URL,
          keywords: data.keywords || [],
          content,
          htmlContent: marked.parse(content),
          url: `/${category}/${slug}`,
          canonical: `${SITE_URL}/${category}/${slug}`,
        });
      }
    }
  }

  walk(CONTENT_DIR);
  posts.sort((a, b) => new Date(b.date) - new Date(a.date));
  return posts;
}

function renderPostCard(post, options = {}) {
  const thumb = escapeHtml(toAbsoluteUrl(post.thumbnail));
  const href = escapeHtml(post.url);
  const title = escapeHtml(post.title);
  const desc = escapeHtml(post.description);
  const date = formatDateDisplay(post.date);
  const label = CATEGORY_LABELS[post.category] || post.category;

  return `
    <a href="${href}" class="card-lift group block overflow-hidden rounded-sm border border-[#0A2A5E]/10 bg-white shadow-md">
      <div class="aspect-video overflow-hidden bg-slate-100">
        <img src="${thumb}" alt="${title}" class="h-full w-full object-cover transition duration-500 group-hover:scale-105" loading="lazy">
      </div>
      <div class="p-5">
        <span class="text-[10px] font-semibold uppercase tracking-[0.2em] text-[#C9A96A]">${escapeHtml(label)}</span>
        <h3 class="mt-2 font-serif text-xl text-[#0A2A5E] line-clamp-2">${title}</h3>
        <time class="mt-2 block text-xs text-slate-500">${date}</time>
        ${options.showDescription !== false ? `<p class="mt-3 text-sm text-slate-600 line-clamp-2">${desc}</p>` : ''}
      </div>
    </a>`;
}

function renderCategoryTabs(activeCategory) {
  return CATEGORIES.map((cat) => {
    const active = cat === activeCategory ? 'active' : '';
    const label = CATEGORY_LABELS[cat];
    return `<a href="/${cat}" class="tab-btn rounded-full border border-[#0A2A5E]/15 px-5 py-2 text-sm font-semibold text-[#0A2A5E] transition hover:border-[#C9A96A] ${active}">${label}</a>`;
  }).join('\n    ');
}

function buildJsonLd(post) {
  const articleType = post.category === 'news' ? 'NewsArticle' : 'Article';
  const imageUrl = toAbsoluteUrl(post.thumbnail);

  const article = {
    '@context': 'https://schema.org',
    '@type': articleType,
    headline: post.title,
    description: post.description,
    image: imageUrl,
    datePublished: post.date,
    dateModified: post.date,
    author: { '@type': 'Organization', name: '더퀸 웨딩홀' },
    publisher: {
      '@type': 'Organization',
      name: '더퀸 웨딩홀',
      logo: { '@type': 'ImageObject', url: LOGO_URL },
    },
    mainEntityOfPage: post.canonical,
  };

  const breadcrumb = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: '더퀸 웨딩홀', item: `${SITE_URL}/` },
      { '@type': 'ListItem', position: 2, name: CATEGORY_LABELS[post.category], item: `${SITE_URL}/${post.category}` },
      { '@type': 'ListItem', position: 3, name: post.title, item: post.canonical },
    ],
  };

  return JSON.stringify([article, breadcrumb]);
}

function renderRelatedPosts(post, allPosts) {
  const related = allPosts
    .filter((p) => p.category === post.category && p.slug !== post.slug)
    .slice(0, 3);

  if (related.length === 0) return '';

  const cards = related.map((p) => renderPostCard(p, { showDescription: false })).join('\n');

  return `
    <section class="mt-16 border-t border-[#C9A96A]/20 pt-12">
      <h2 class="mb-8 text-center font-serif text-2xl text-[#0A2A5E]">관련 글</h2>
      <div class="grid gap-6 sm:grid-cols-3 not-prose">${cards}</div>
    </section>`;
}

function generatePostPages(posts) {
  const postTemplate = readFile(path.join(TEMPLATES_DIR, 'post.html'));

  for (const post of posts) {
    const html = replaceAll(postTemplate, {
      TITLE: escapeHtml(post.title),
      DESCRIPTION: escapeHtml(post.description),
      CANONICAL: post.canonical,
      OG_IMAGE: toAbsoluteUrl(post.thumbnail),
      JSON_LD: buildJsonLd(post),
      CATEGORY: post.category,
      CATEGORY_LABEL: CATEGORY_LABELS[post.category],
      CATEGORY_TABS: renderCategoryTabs(post.category),
      DATE_ISO: post.date,
      DATE_DISPLAY: formatDateDisplay(post.date),
      HERO_IMAGE: post.thumbnail
        ? `<div class="mx-auto max-w-3xl overflow-hidden rounded-sm"><img src="${escapeHtml(toAbsoluteUrl(post.thumbnail))}" alt="${escapeHtml(post.title)}" class="w-full object-cover" loading="eager"></div>`
        : '',
      CONTENT: post.htmlContent,
      RELATED_POSTS: renderRelatedPosts(post, posts),
      TITLE_JS: JSON.stringify(post.title),
      DESCRIPTION_JS: JSON.stringify(post.description),
      OG_IMAGE_JS: JSON.stringify(toAbsoluteUrl(post.thumbnail)),
      CANONICAL_JS: JSON.stringify(post.canonical),
      KAKAO_JS_KEY: JSON.stringify(KAKAO_JS_KEY),
      NAV_NEWS: 'active',
    });

    const outPath = path.join(ROOT, post.category, `${post.slug}.html`);
    writeFile(outPath, html);
    console.log(`  ✓ ${post.category}/${post.slug}.html`);
  }
}

function generateListPages(posts) {
  const listTemplate = readFile(path.join(TEMPLATES_DIR, 'list.html'));

  for (const category of CATEGORIES) {
    const categoryPosts = posts.filter((p) => p.category === category);
    const cards = categoryPosts.length
      ? categoryPosts.map((p) => renderPostCard(p)).join('\n')
      : '<p class="col-span-full text-center text-slate-500 py-12">아직 게시된 글이 없습니다.</p>';

    const html = replaceAll(listTemplate, {
      LIST_TITLE: CATEGORY_LABELS[category],
      LIST_DESCRIPTION: CATEGORY_INTROS[category],
      LIST_INTRO: CATEGORY_INTROS[category],
      CANONICAL: `${SITE_URL}/${category}`,
      CATEGORY_TABS: renderCategoryTabs(category),
      POST_CARDS: cards,
    });

    const outPath = path.join(ROOT, category, 'index.html');
    writeFile(outPath, html);
    console.log(`  ✓ ${category}/index.html`);
  }
}

function updateHomeLatestPosts(posts) {
  const indexPath = path.join(ROOT, 'index.html');
  let indexHtml = readFile(indexPath);

  const latest = posts.slice(0, 3);
  const cards = latest.length
    ? latest.map((p) => renderPostCard(p)).join('\n')
    : '<p class="col-span-full text-center text-slate-500">곧 새로운 이야기가 업데이트됩니다.</p>';

  const section = `
  <!-- LATEST_POSTS_START -->
  <section class="relative w-full overflow-hidden bg-white py-24 lg:py-32">
    <div class="relative mx-auto max-w-7xl px-6">
      <div class="mb-16 text-center">
        <div class="reveal mb-5 flex items-center justify-center gap-3">
          <span class="h-px w-10 bg-gold"></span>
          <span class="text-[11px] font-semibold uppercase tracking-[0.32em] text-gold">The Queen Stories</span>
          <span class="h-px w-10 bg-gold"></span>
        </div>
        <h2 class="reveal rd-1 font-serif text-4xl leading-tight text-royal-900 sm:text-5xl">더퀸 스토리</h2>
        <p class="reveal rd-2 mx-auto mt-4 max-w-xl text-slate-600">리모델링, 웨딩 가이드, 리얼 예식, 퀸즈테이블까지 — 더퀸의 이야기를 만나보세요.</p>
      </div>
      <div class="grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
        ${cards}
      </div>
      <div class="mt-12 text-center">
        <a href="/news" class="btn-shimmer inline-flex items-center gap-2 rounded-full border-2 border-royal-900/20 px-8 py-3 text-sm font-semibold text-royal-900 transition hover:bg-royal-900 hover:text-white">
          모든 스토리 보기 →
        </a>
      </div>
    </div>
  </section>
  <!-- LATEST_POSTS_END -->`;

  const markerRegex = /<!-- LATEST_POSTS_START -->[\s\S]*?<!-- LATEST_POSTS_END -->/;
  if (!markerRegex.test(indexHtml)) {
    console.warn('  ⚠ LATEST_POSTS markers not found in index.html — skipping home update');
    return;
  }

  indexHtml = indexHtml.replace(markerRegex, section.trim());
  writeFile(indexPath, indexHtml);
  console.log('  ✓ index.html (latest posts section)');
}

function generateSitemap(posts) {
  const urls = [...BASE_SITEMAP_URLS];

  for (const category of CATEGORIES) {
    urls.push({
      loc: `${SITE_URL}/${category}`,
      changefreq: 'weekly',
      priority: '0.8',
    });
  }

  for (const post of posts) {
    urls.push({
      loc: post.canonical,
      changefreq: 'monthly',
      priority: '0.7',
      lastmod: post.date,
    });
  }

  const urlEntries = urls.map((u) => {
    let entry = `  <url>\n    <loc>${escapeHtml(u.loc)}</loc>\n`;
    if (u.lastmod) entry += `    <lastmod>${u.lastmod}</lastmod>\n`;
    entry += `    <changefreq>${u.changefreq}</changefreq>\n    <priority>${u.priority}</priority>\n  </url>`;
    return entry;
  }).join('\n');

  const xml = `<?xml version="1.0" encoding="UTF-8"?>\n${AUTO_COMMENT}<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">\n${urlEntries}\n</urlset>\n`;

  writeFile(path.join(ROOT, 'sitemap.xml'), xml);
  console.log(`  ✓ sitemap.xml (${urls.length} URLs)`);
}

function generateRss(posts) {
  const items = posts.slice(0, 20).map((post) => `    <item>
      <title>${escapeHtml(post.title)}</title>
      <link>${post.canonical}</link>
      <description>${escapeHtml(post.description)}</description>
      <pubDate>${toRfc822(post.date)}</pubDate>
      <guid isPermaLink="true">${post.canonical}</guid>
    </item>`).join('\n');

  const xml = `<?xml version="1.0" encoding="UTF-8"?>\n${AUTO_COMMENT}<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>더퀸 웨딩홀 스토리</title>
    <link>${SITE_URL}</link>
    <description>더퀸 웨딩홀의 소식, 웨딩 가이드, 리얼 웨딩, 퀸즈테이블 이야기</description>
    <language>ko</language>
    <atom:link href="${SITE_URL}/rss.xml" rel="self" type="application/rss+xml"/>
${items}
  </channel>
</rss>\n`;

  writeFile(path.join(ROOT, 'rss.xml'), xml);
  console.log(`  ✓ rss.xml (${Math.min(posts.length, 20)} items)`);
}

function main() {
  console.log('Building content...\n');

  const posts = scanPosts();
  console.log(`Found ${posts.length} published post(s)\n`);

  console.log('Generating post pages:');
  generatePostPages(posts);

  console.log('\nGenerating list pages:');
  generateListPages(posts);

  console.log('\nUpdating home page:');
  updateHomeLatestPosts(posts);

  console.log('\nGenerating feeds:');
  generateSitemap(posts);
  generateRss(posts);

  console.log('\nDone.');
}

main();
